version: "2"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - SERVER_PROFILE_PARENT=MONITORING
      - SERVER_PROFILE_MONITORING_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_MONITORING_PATH=monitoring/pingdirectory/jolokia
      - SERVER_PROFILE_MONITORING_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/arnaudlacour/katacoda.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet

networks:
    pingnet: